### ISSUE TITLE
Strategy to avoid Memory Leaks?

### ISSUE THREAD

**Issue by wowcut** [paragi/timexe#4]
Hi, I am looking for a library that helps me to manage multiple timers and to **avoid memory leaks** at the same time. This is why I am curious: what is your strategy to avoid memory leaks? 
I am not sure I understand your code 100%, but what I see  [here](https://github.com/paragi/timexe/blob/67cb3b48532f1febe95a87a5a3a0b5876c0240bf/timexe.js#L259) I guess that you are generating a new timer for each new job - what seems to be a good way into generating huge meory leaks. Am I wrong?

**Comment by paragi** [comment]
Hi wowcut 

Memory leaks is always a serious issue. I try very hard to avoid it :)
I don't see any problem with the line you refer to. You have to allocate memory for each timer in a list, and the function to execute.
Every 24 hours or so, all timers run out and is re-initiated. The pointer referring to it is overwrite with the new one. The garbage collection should remove any object that is not referred to. 

I haven't had any issues with timexe in production, for the past few years. 
However I haven't included a test for memory leak. That would be a useful test to add.
Would you care to give it a try? (unfortunately I'm unable to set aside the time at the moment :(

Since I haven't made it part of the test suite, it would be difficult to give guaranties. But if you find any, I will correct it as fast as I can :)

How many timers do you expect? and how long do you expect them to run?

**Comment by wowcut** [comment]
Thanks for your info, very interesting! To answer your question: I would expect exactly _one_ timer that handles all calls - I was expecting that a manager of setTimeouts would only need one master clock. However, I see your point. Maybe I will look later deeper into it, when my todo list shrinked a bit.
Have a nice year!

**Comment by paragi** [comment]
The code is optimized to have as precise timing as possible, with low CPU usages. (The package is used in embedded systems)  
Interpreting commands is very CPU consuming, when you have to do it every few milliseconds.
Only a few references and the timer object is stored for each timer (unless you spawn a new function for each timer) So memory usage should be at a minimum. Especially in your case.

Happy coding :)


Functions  and (its always by reference)  it doesn't take up much memory
The code is optimized 
I use multiple timers, to
